package com.tr.dagdem.model.user;

// Generated Nov 14, 2008 11:39:19 AM by Hibernate Tools 3.2.2.GA

import java.util.Date;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import javax.validation.constraints.Max;
import javax.validation.constraints.NotNull;

import com.google.common.collect.Sets;
import com.tr.dagdem.model.sale.MusteriSatisTable;

/**
 * KullaniciTable generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "KULLANICI_TABLE")
public class KullaniciTable implements java.io.Serializable {

	private long id;
	private String kullanici;
	private String sifre;
	private String isim;
	private String soyisim;
	private String email;
	private Long gsm;
	private Date tarih;
	private Date kapamaTarih;
	
//	private Set<MusteriSatisTable> kullanicininSatislari = Sets.newHashSet();
//
//	@OneToMany(cascade=CascadeType.ALL,fetch=FetchType.LAZY,mappedBy="pk.kullanici")
//	public Set<MusteriSatisTable> getKullanicininSatislari() {
//		return kullanicininSatislari;
//	}
//
//	public void setKullanicininSatislari(Set<MusteriSatisTable> kullanicininSatislari) {
//		this.kullanicininSatislari = kullanicininSatislari;
//	}
	
	public KullaniciTable() {
	}

	public KullaniciTable(long id,String isim, String sifre, String email, Long gsm,Date tarih, Date kapamaTarih) 
	{	
		this.id = id;
		this.isim = isim;
		this.sifre = sifre;
		this.email = email;
		this.gsm = gsm;
		this.tarih = tarih;
		this.kapamaTarih = kapamaTarih;
	}
	
	@Id
    @Column(name = "KULLANICI_ID", unique = true, nullable = false, precision = 23, scale = 0)
    @NotNull
    @GeneratedValue(strategy = GenerationType.IDENTITY)
//    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "faydalanan_mbb_seq")
//    @SequenceGenerator(name = "faydalanan_mbb_seq", sequenceName = "FAYDALANAN_MBB_SEQ", allocationSize = 1)
    public Long getId()
    {
        return this.id;
    }

    public void setId(Long id)
    {
        this.id = id;
    }
    
	
	@Column(name = "KULLANICI", nullable = false, length = 12)
	@NotNull
	@Max(12)
	public String getKullanici() {
		return this.kullanici;
	}

	public void setKullanici(String kullanici) {
		this.kullanici = kullanici;
	}
	
	@Column(name = "SIFRE", length = 12)
	@Max(12)
	public String getSifre() {
		return this.sifre;
	}

	public void setSifre(String sifre) {
		this.sifre = sifre;
	}


	@Column(name = "ISIM", length = 20)
	@Max(20)
	public String getIsim() {
		return this.isim;
	}

	public void setIsim(String isim) {
		this.isim = isim;
	}
	
    @Column(name = "SOYISIM", length = 20)
    @Max(20)
    public String getSoyisim()
    {
        return this.soyisim;
    }

    public void setSoyisim(String soyisim)
    {
        this.soyisim = soyisim;
    }

	@Column(name = "EMAIL", length = 50)
	@Max(50)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "GSM", precision = 10, scale = 0)
	public Long getGsm() {
		return this.gsm;
	}

	public void setGsm(Long gsm) {
		this.gsm = gsm;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "TARIH", length = 7)
	public Date getTarih() {
		return this.tarih;
	}

	public void setTarih(Date tarih) {
		this.tarih = tarih;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "KAPAMA_TARIH", length = 7)
	public Date getKapamaTarih() {
		return this.kapamaTarih;
	}

	public void setKapamaTarih(Date kapamaTarih) {
		this.kapamaTarih = kapamaTarih;
	}
	
}
