package com.tr.dagdem.model.dealer;

// Generated Nov 14, 2008 11:39:19 AM by Hibernate Tools 3.2.2.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import org.apache.commons.lang3.StringUtils;
import javax.validation.constraints.Max;
import javax.validation.constraints.NotNull;

import com.tr.dagdem.model.product.UrunTanimTable;

/**
 * KullaniciTable generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "SATICI_TANIM_TABLE")
public class SaticiTanimTable implements java.io.Serializable {

	private long id;
	private String saticiAdi;
	private String saticiSoyadi;
	private String plaka;
	private String email;
	private boolean aktif;
	private Long gsm;
	private Date tarih;
	
	private Set<UrunTanimTable> saticininUrunleri = new HashSet<UrunTanimTable>();
	
	private Set<UrunTanimTable> saticininIadeUrunleri = new HashSet<UrunTanimTable>();
	
	public SaticiTanimTable() {
	}

	public SaticiTanimTable(long id,String saticiAdi, String saticiSoyadi, String email, Long gsm,Date tarih, boolean aktif) 
	{	
		this.id = id;
		this.saticiAdi = saticiAdi;
		this.saticiSoyadi = saticiSoyadi;
		this.email = email;
		this.gsm = gsm;
		this.tarih = tarih;
		this.aktif = aktif;
	}
	
	@Id
    @Column(name = "SATICI_ID", unique = true, nullable = false, precision = 23, scale = 0)
    @NotNull
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    public Long getId()
    {
        return this.id;
    }

    public void setId(Long id)
    {
        this.id = id;
    }
    
	@Column(name = "SATICI_ADI", length = 100)
	@Max(100)
	public String getSaticiAdi() {
		return this.saticiAdi;
	}

	public void setSaticiAdi(String saticiAdi) {
		this.saticiAdi = saticiAdi;
	}
	
    @Column(name = "SATICI_SOYADI", length = 100)
    @Max(100)
    public String getSaticiSoyadi()
    {
        return this.saticiSoyadi;
    }

    public void setSaticiSoyadi(String saticiSoyadi)
    {
        this.saticiSoyadi = saticiSoyadi;
    }

	@Column(name = "EMAIL", length = 50)
	@Max(50)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "GSM", precision = 10, scale = 0)
	public Long getGsm() {
		return this.gsm;
	}

	public void setGsm(Long gsm) {
		this.gsm = gsm;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "TARIH", length = 7)
	public Date getTarih() {
		return this.tarih;
	}

	public void setTarih(Date tarih) {
		this.tarih = tarih;
	}
	
	@Column(name="AKTIF")
	public boolean isAktif() {
		return aktif;
	}
	
	public void setAktif(boolean aktif) {
		this.aktif = aktif;
	}
	
	@Column(name = "PLAKA", length = 12)
	@Max(12)
	public String getPlaka() {
		return plaka;
	}
	public void setPlaka(String plaka) {
		this.plaka = plaka;
	}
	
	@Transient
	public String getSaticiAdiSoyadi()
	{
		return StringUtils.join(new Object[]{this.getSaticiAdi()," ",this.getSaticiSoyadi()}).toUpperCase();
	}

	@Transient
	public Set<UrunTanimTable> getSaticininUrunleri() {
		return saticininUrunleri;
	}
	
	public void setSaticininUrunleri(Set<UrunTanimTable> saticininUrunleri) {
		this.saticininUrunleri = saticininUrunleri;
	}
	
	@Transient
	public Set<UrunTanimTable> getSaticininIadeUrunleri() {
		return saticininIadeUrunleri;
	}
	
	public void setSaticininIadeUrunleri(Set<UrunTanimTable> saticininIadeUrunleri) {
		this.saticininIadeUrunleri = saticininIadeUrunleri;
	}
}
